version: "2"
run:
  build-tags:
    - exclude_graphdriver_btrfs containers_image_openpgp remote
linters:
  enable:
    - cyclop
    - govet
    - funlen
    - gocognit
    - godoclint
    - godot
    - misspell
    - mnd
    - nestif
    - nlreturn
    - prealloc
    - whitespace
  disable:
    - wsl
    - depguard
  exclusions:
    paths:
      - docs/docs.go
